### ISSUE TITLE
Last login is not working

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#22]
Hi,

After some login/logout series, the last login time displayed in 3 dots menu is not updated. It's always at Last login: 01.01.70 00:00. 

I don't have a fix for this one, I'm not a js player. 

For information, the time is updated for clients. 
Other information, in webapp very verbose log, we can see the db userLastLogin entry be updated twice: at login and at logout. 

K.

**Comment by Offerel** [comment]
I don't know if i should change this. The idea is it, to not write the date for every login process. Thats why the date is only updated in database for the last sync. Currently this is only done by startupsync from bowser AddOn or by Browser AddOn Export. Only then i can be sure, that bookmarks are in sync with browser and use this as last sync date. Every change after that date will be assumed as change in bookmarks and synced to the devices with next sync.

If i change this behavior, this will complicate syncing behavior a lot, meaning also that a sync will take a lot longer as of now. For example, i have around 300 bookmarks. Sync will be done i a blink of a second (after http requests are done). When i have to implement other sync schemas, it will take more than 30 seconds at the client, depending on the client speed. In my measures this was 30 seconds on my gaming PC with Firefox and 45 seconds on Kiwi on an Samsung Galaxy S20.

That's why, if i didn't found a faster way of doing a reliable sync, i will keep the current dates.

**Comment by kayceegb** [comment]
I'm no sure we are talking about the same think. Don't you refer to lastseen in client table ? This seems to work correctly and, it is in fact, what I refer above when I say  "the time is updated for clients".

What I'm talking about, is the userLastLogin from users table. In contrary to what log says, it is never updated. I tried logins/logouts, exports, restart client, add new bm to generate sync. Nothing to do, the table entry stay empty.

Is it desired ?

**Comment by Offerel** [comment]
Ahh, I see. Correct, this is currently not used and was actually reserved for another function.

**Comment by kayceegb** [comment]
You mean it was not linked to the "Last login" you see when you open 3 dots menu ?

**Comment by Offerel** [comment]
Currently the menu should display the latest sync date. the other date is unused for now.

**Comment by kayceegb** [comment]
I see. I have since this issue creation, done several exports, login/logout series, syncs, page force refresh, and the information is still not updated. :/
If it is related to last lync, maybe "Last login" should be changed to "Last synchronization" or something like that ?

**Comment by Offerel** [comment]
I will think about this. Maybe i have some idea for future date handling.

**Comment by kayceegb** [comment]
Ok. That is not high priority. I just thought that something is not working like it should and that I should report it :)

**Comment by kayceegb** [comment]
Because I started looking at code by curiosity and I'm more familiar with php, I seen this and after a little fix, the data is updated.

    diff --git a/index.php b/index.php
    index 4d09e37..081499d 100644
    --- a/index.php
    +++ b/index.php
    @@ -1248,7 +1248,7 @@ function htmlHeader($ud) {
            <div class='hline'></div>
        </div>
        <button>&#8981;</button><input type='search' name='bmsearch' value=''>
    -   <a id='mprofile' title=\"Last login: ".date("d.m.y H:i",$ud['userOldLogin'])."\">My Bookmarks</a>
    +   <a id='mprofile' title=\"Last login: ".date("d.m.y H:i",(int)$ud['userOldLogin'])."\">My Bookmarks</a>
            </div>";
 
        if($ud['userType'] == 2) {
    @@ -1694,7 +1694,7 @@ function doLogin($database,$realm) {
 
                    if($seid != $userData[0]['sessionID']) {
                        e_log(8,"Save session to database.");
    -                   $query = "UPDATE `users` SET `userLastLogin`= $aTime, `sessionID` = '$seid', `userOldLogin`= $oTime WHERE `userID` = '$uid'";
    +                   $query = "UPDATE `users` SET `userLastLogin`= $aTime, `sessionID` = '$seid', `userOldLogin`= '$oTime' WHERE `userID` = '$uid'";
                        $db->exec($query);
                        e_log(9,$query);
                    }
    @@ -1773,4 +1773,4 @@ function initDB($database,$suser,$spwd) {
        }
        $db = NULL;
     }
    -?>
    \ No newline at end of file
    +?>

**Comment by Offerel** [comment]
I have added you changes in commit [96791b0](https://github.com/Offerel/SyncMarks-Webapp/commit/96791b0d4901c61fab9e75dbb30c25cb991ca04e)

**Comment by kayceegb** [comment]
You said that you had something different in mind, but I'm happy to see that you took that, in the meanwhile :D
