### ISSUE TITLE
Change to choose select password

### ISSUE THREAD

**Issue by johmor52** [Offerel/SyncMarks-Webapp#66]
I have installed 1.4.2 in Linux Buster with php7.3.
When came to sending login for new user, the mail couldn't be sent.
It's a setting in php I suppose, but it would be good if I could set a key in config.inc.php to let me choose a password myself.
That would make it easier to use webapp in own network.

**Comment by Offerel** [comment]
Im using the standard php mail functionality for sending the mail, because this is the easiest configuration. The admin for the server has to configure the php mail settings properly. For easy standard mails like this, it's enough to use something like nullmailer package.

But what do you mean with "but it would be good if I could set a key in config.inc.php to let me choose a password myself"? The password for the mailhost?

**Comment by johmor52** [comment]
I will setup a working mail tomorrow (if time enough) in my php so I can test function for webapp - extension without having a extra tab open. Then I hope to find out more about syncing to Chrome and Edge.

I mean to be able to set the first password myself for every user.

**Comment by Offerel** [comment]
Set a password manually makes only really sense, when a new user can do this by himself. On the other side, manually entering a password by the admin for the user, is at least in my eyes a bad practice. In this case, the admin gets knowledge about the user password, which is not a good idea. On top, this make an admin responsible for user credentials. Now combine this with authorities like china, or turkey and you get the problem.

By automating this process, the admin has no idea, what the user will use as password. Request from an authority can be denied, at least requesting the password. 

The only other option, i.e. let the user register by himself, is problematic in other terms. 

I can understand why you want this feature. But for now, i would keep this as it is. Maybe i change this in future release, so that the automatic way will be default and optionally, the password generating process can be enabled manually. I have currently no plan how i will do this. The next full release will include MySQL support, maybe i add additionally a way for your request in some way.

**Comment by Offerel** [comment]
Only for testing purposes: I have added now a password field, when an admin creates a new user. If the admin enter a password here, this manually entered password is used when creating the user. If the field is left empty, the password is created automatically by the same rules as before. This change isn't commuted as of yet, because i have to check some MySQL functions for the next release, but it is working so far. Is this what you want?

**Comment by johmor52** [comment]
Perfect!

Den 26 mars 2021 13:24:45 skrev Offerel ***@***.***>:
